package com.bigp.rubiksolver.cube.solver.twophase

import com.bigp.rubiksolver.cube.solver.common.CubieCube
import com.bigp.rubiksolver.cube.solver.common.SolveProgress

/**
 * Move and pruning tables for the two-phase (Kociemba) 3x3 solver.
 *
 * Roughly 8 MB of lookup tables, built once by breadth-first search and then cached in memory for
 * the life of the process. Generation runs in about a second on a phone; the caller is expected to
 * do it off the main thread and can persist the result with [writeTo] / [readFrom] so later runs
 * skip it entirely.
 *
 * ### Coordinates
 * Phase 1 drives corner twist, edge flip and the middle-slice edge *positions* to zero, which lands
 * the cube in the group generated by U, D, R2, L2, F2 and B2. Phase 2 then fixes corner
 * permutation, U/D edge permutation and slice edge permutation without leaving that group.
 *
 * Two pruning tables per phase are combined with `max`, which stays admissible because every table
 * measures a relaxation of the same problem.
 */
object TwoPhaseTables {

    const val TWIST_COUNT = 2187
    const val FLIP_COUNT = 2048
    const val SLICE_COUNT = 495
    const val CORNER_PERM_COUNT = 40320
    const val EDGE8_PERM_COUNT = 40320
    const val SLICE_PERM_COUNT = 24

    private const val ALL_MOVES = 18
    private val PHASE2 = CubieCube.PHASE2_MOVE_INDICES

    lateinit var twistMove: Array<IntArray>; private set
    lateinit var flipMove: Array<IntArray>; private set
    lateinit var sliceMove: Array<IntArray>; private set
    lateinit var cornerPermMove: Array<IntArray>; private set
    lateinit var edge8PermMove: Array<IntArray>; private set
    lateinit var slicePermMove: Array<IntArray>; private set

    lateinit var prunTwistSlice: ByteArray; private set
    lateinit var prunFlipSlice: ByteArray; private set
    lateinit var prunCornerSlice: ByteArray; private set
    lateinit var prunEdge8Slice: ByteArray; private set

    @Volatile
    private var built = false

    /** Bumped whenever the table layout changes, so stale caches are ignored. */
    const val FORMAT_VERSION = 1

    @Synchronized
    fun ensureBuilt(onProgress: (SolveProgress) -> Unit = {}) {
        if (built) return
        onProgress(SolveProgress("Building move tables", 0.05f))
        buildMoveTables()
        onProgress(SolveProgress("Building pruning tables", 0.35f))
        prunTwistSlice = bfs(TWIST_COUNT, SLICE_COUNT, 0, CubieCube.SOLVED_UD_SLICE, twistMove, sliceMove, ALL_MOVES)
        onProgress(SolveProgress("Building pruning tables", 0.55f))
        prunFlipSlice = bfs(FLIP_COUNT, SLICE_COUNT, 0, CubieCube.SOLVED_UD_SLICE, flipMove, sliceMove, ALL_MOVES)
        onProgress(SolveProgress("Building pruning tables", 0.75f))
        prunCornerSlice = bfs(CORNER_PERM_COUNT, SLICE_PERM_COUNT, 0, 0, cornerPermMove, slicePermMove, PHASE2.size)
        onProgress(SolveProgress("Building pruning tables", 0.9f))
        prunEdge8Slice = bfs(EDGE8_PERM_COUNT, SLICE_PERM_COUNT, 0, 0, edge8PermMove, slicePermMove, PHASE2.size)
        built = true
        onProgress(SolveProgress("Ready", 1f))
    }

    private fun buildMoveTables() {
        twistMove = Array(TWIST_COUNT) { c ->
            val cube = CubieCube.setTwist(c)
            IntArray(ALL_MOVES) { m -> cube.applied(CubieCube.MOVES[m]).twist() }
        }
        flipMove = Array(FLIP_COUNT) { c ->
            val cube = CubieCube.setFlip(c)
            IntArray(ALL_MOVES) { m -> cube.applied(CubieCube.MOVES[m]).flip() }
        }
        sliceMove = Array(SLICE_COUNT) { c ->
            val cube = CubieCube.setUdSlice(c)
            IntArray(ALL_MOVES) { m -> cube.applied(CubieCube.MOVES[m]).udSlice() }
        }
        cornerPermMove = Array(CORNER_PERM_COUNT) { c ->
            val cube = CubieCube.setCornerPermutation(c)
            IntArray(PHASE2.size) { i -> cube.applied(CubieCube.MOVES[PHASE2[i]]).cornerPermutation() }
        }
        edge8PermMove = Array(EDGE8_PERM_COUNT) { c ->
            val cube = CubieCube.setEdge8Permutation(c)
            IntArray(PHASE2.size) { i -> cube.applied(CubieCube.MOVES[PHASE2[i]]).edge8Permutation() }
        }
        slicePermMove = Array(SLICE_PERM_COUNT) { c ->
            val cube = CubieCube.setSlicePermutation(c)
            IntArray(PHASE2.size) { i -> cube.applied(CubieCube.MOVES[PHASE2[i]]).slicePermutation() }
        }
    }

    /**
     * Breadth-first distance table over the product of two coordinates.
     *
     * Index layout is `a * bCount + b`. Values are capped at 127 but real depths never come close.
     */
    private fun bfs(
        aCount: Int,
        bCount: Int,
        goalA: Int,
        goalB: Int,
        aMove: Array<IntArray>,
        bMove: Array<IntArray>,
        moveCount: Int,
    ): ByteArray {
        val size = aCount * bCount
        val dist = ByteArray(size).also { it.fill(-1) }
        val goal = goalA * bCount + goalB
        dist[goal] = 0
        // One queue holding every reachable state in breadth-first order; it can never need more
        // than `size` slots because a state is enqueued only when its distance is first written.
        val queue = IntArray(size)
        queue[0] = goal
        var head = 0
        var tail = 1
        while (head < tail) {
            val state = queue[head++]
            val depth = dist[state] + 1
            val rowA = aMove[state / bCount]
            val rowB = bMove[state % bCount]
            for (m in 0 until moveCount) {
                val candidate = rowA[m] * bCount + rowB[m]
                if (dist[candidate].toInt() == -1) {
                    dist[candidate] = depth.toByte()
                    queue[tail++] = candidate
                }
            }
        }
        return dist
    }

    // ---- Persistence ---------------------------------------------------------------------

    /** Writes the four pruning tables so a later run can skip the breadth-first searches. */
    fun writeTo(sink: java.io.OutputStream) {
        val out = java.io.DataOutputStream(java.io.BufferedOutputStream(sink, 1 shl 16))
        out.writeInt(FORMAT_VERSION)
        for (table in listOf(prunTwistSlice, prunFlipSlice, prunCornerSlice, prunEdge8Slice)) {
            out.writeInt(table.size)
            out.write(table)
        }
        out.flush()
    }

    /**
     * Restores pruning tables written by [writeTo]. Move tables are always rebuilt because they are
     * cheap; only the breadth-first searches are worth caching.
     *
     * Returns false when the stream does not match the current format, in which case the caller
     * should fall back to [ensureBuilt].
     */
    @Synchronized
    fun readFrom(source: java.io.InputStream, onProgress: (SolveProgress) -> Unit = {}): Boolean {
        if (built) return true
        return try {
            val input = java.io.DataInputStream(java.io.BufferedInputStream(source, 1 shl 16))
            if (input.readInt() != FORMAT_VERSION) return false
            val expected = intArrayOf(
                TWIST_COUNT * SLICE_COUNT,
                FLIP_COUNT * SLICE_COUNT,
                CORNER_PERM_COUNT * SLICE_PERM_COUNT,
                EDGE8_PERM_COUNT * SLICE_PERM_COUNT,
            )
            val tables = ArrayList<ByteArray>(4)
            for (size in expected) {
                if (input.readInt() != size) return false
                val buffer = ByteArray(size)
                input.readFully(buffer)
                tables += buffer
            }
            onProgress(SolveProgress("Building move tables", 0.4f))
            buildMoveTables()
            prunTwistSlice = tables[0]
            prunFlipSlice = tables[1]
            prunCornerSlice = tables[2]
            prunEdge8Slice = tables[3]
            built = true
            onProgress(SolveProgress("Ready", 1f))
            true
        } catch (_: java.io.IOException) {
            false
        }
    }

    val isBuilt: Boolean get() = built
}
